dist: xenial
language: c
compiler: gcc

before_install:
 - sudo apt-get update
 - sudo apt-get install check gfortran libopenmpi-dev openmpi-bin numactl autoconf libnuma-dev doxygen

script: autoreconf -i && ./configure CC=mpicc CXX=mpic++ FC=mpif90 && make -j4 && CC=mpicc CXX=mpic++ FC=mpif90 make distcheck
